### ISSUE TITLE
-[__NSCFCalendar components:fromDate:]: date cannot be nil

### ISSUE THREAD

**Issue by nilskasseckert** [jaykz52/CKCalendar#40]
Hello,
I use in my App your Calendar. This morning I build my Project again and since I get following Error:
-[__NSCFCalendar components:fromDate:]: date cannot be nil
I mean really, what do you think that operation is supposed to mean with a nil date?
An exception has been avoided for now.
A few of these errors are going to be reported with this complaint, then further violations will simply silently do whatever random thing results from the nil.
Here is the backtrace where this occurred this time (some frames may be missing due to compiler optimizations):

This Error comes by following line:
CKCalendarView *calendarSubView = [[CKCalendarView alloc] init];[/code]
Is this a Issue or is it because iOS 7 on my Test Device?

**Comment by fastred** [comment]
Hello,
I've got the same exception on iOS 6.1, both on a simulator and a device.
From what I've found it's caused by sending setDate to DateButton with nil on line [274 in CKCalendarView.m](https://github.com/jaykz52/CKCalendar/blob/master/Source/CKCalendarView.m#L274):

``` objc
dateButton.date = nil;
```

If I'm not missing any edge cases, this line can be deleted, because button is removed from superview on the next line and added back only after it's been [set with a correct date](https://github.com/jaykz52/CKCalendar/blob/master/Source/CKCalendarView.m#L296).
