### ISSUE TITLE
Wrong position in the days of the month

### ISSUE THREAD

**Issue by crazyramirez** [jaykz52/CKCalendar#5]
I have found that when it recognizes a month starts the first day mid-week schedule is set incorrectly.
Maybe this can be a solution to the problem of managing the day in the week:

Declare a variable in CKCalendarView.h BOOL (Ej. BOOL moveFirstRow).

And change this lines of code:

(CGRect)calculateDayCellFrame:(NSDate *)date {
int row = [self weekNumberInMonthForDate:date] - 1;
int placeInWeek = (([self dayOfWeekForDate:date] - 1) - self.calendar.firstWeekday + 8) % 7;

if (row == -1)
moveFirstRow = YES;

if (moveFirstRow == YES)
return CGRectMake(placeInWeek \* (self.cellWidth + CELL_BORDER_WIDTH), (row \* (self.cellWidth + CELL_BORDER_WIDTH)) + CGRectGetMaxY(self.daysHeader.frame) + CELL_BORDER_WIDTH + (self.cellWidth + CELL_BORDER_WIDTH), self.cellWidth, self.cellWidth);
else 
return CGRectMake(placeInWeek \* (self.cellWidth + CELL_BORDER_WIDTH), (row \* (self.cellWidth + CELL_BORDER_WIDTH)) + CGRectGetMaxY(self.daysHeader.frame) + CELL_BORDER_WIDTH, self.cellWidth, self.cellWidth);

}

(void)moveCalendarToNextMonth {
moveFirstRow = NO;
NSDateComponents\* comps = [[NSDateComponents alloc]init];
[comps setMonth:1];
self.monthShowing = [self.calendar dateByAddingComponents:comps toDate:self.monthShowing options:0];
}

(void)moveCalendarToPreviousMonth {
moveFirstRow = NO;
self.monthShowing = [[self firstDayOfMonthContainingDate:self.monthShowing] dateByAddingTimeInterval:-100000];
}

With this solution when it finds that the row = -1, add the cell size and the separator, adjusting correctly.
On the other hand this function checks each time it changes from month.

It may not be the right solution, but it works :)

**Comment by jaykz52** [comment]
Can you give me an example of a month/year/starting day (sunday or monday) that exhibits this problem?

**Comment by ghost** [comment]
Also see this issue on my iPad (iOS5), UK region, showing July 2012, week starting Monday.

I have submitted a fix in a pull-request for you. The fix is essentially to return a zero-based week number, with a change in calculateDayCellFrame to remove the -1.
- (int)weekNumberInMonthForDate:(NSDate *)date {
  // Return zero-based week in month
  NSDateComponents *compsForFirstDayInMonth = [self.calendar components:(NSWeekOfYearCalendarUnit) fromDate:_monthShowing];
  NSDateComponents *comps = [self.calendar components:(NSWeekOfYearCalendarUnit) fromDate:date];
  return comps.weekOfYear - compsForFirstDayInMonth.weekOfYear;
  }
- (CGRect)calculateDayCellFrame:(NSDate *)date {
  int row = [self weekNumberInMonthForDate:date];
  int placeInWeek = (([self dayOfWeekForDate:date] - 1) - self.calendar.firstWeekday + 8) % 7;
  
  return CGRectMake(placeInWeek \* (self.cellWidth + CELL_BORDER_WIDTH), (row \* (self.cellWidth + CELL_BORDER_WIDTH)) + CGRectGetMaxY(self.daysHeader.frame) + CELL_BORDER_WIDTH, self.cellWidth, self.cellWidth);
  }

**Comment by jaykz52** [comment]
closed by pull request #7
