### ISSUE TITLE
Customisation calendar by putting background image on date.

### ISSUE THREAD

**Issue by farazhaider88** [jaykz52/CKCalendar#74]
1> is there any way i can put image on date item background to show it as highlighted?

**Comment by farazhaider88** [comment]
is there any update on this??

**Comment by farazhaider88** [comment]
??

**Comment by brendensuarez** [comment]
I could use this too, but opted out to avoid customizing the code. It wouldn't be hard; just add a `UIImage` to the `CKDateItem` and make use of it in the render code.

**Comment by farazhaider88** [comment]
can you please give me hint of how can i do this ?

**Comment by brendensuarez** [comment]
@farazhaider88 Add a `UIImage` to [`DateItem`](https://github.com/jaykz52/CKCalendar/blob/master/Source/CKCalendarView.h#L20) so that you can [customize each date item from your delegate](https://github.com/jaykz52/CKCalendar/blob/master/Source/CKCalendarView.h#L73). You need to add the image to the `dateButton` [after you call the delegate method](https://github.com/jaykz52/CKCalendar/blob/master/Source/CKCalendarView.m#L310).

That should be all the details you need to code a solution and share it with us.
